number_of_way_points: 100
agent_radius: 0.3535533905932738
verbose: false

collision_cost_const: 1000000.
smooth_acceleration_cost_const : 1.0

variable_delta: false

pre_iteration: 0
growth_iteration: 10000
growth_rate: 1.001

max_iteration: 10000

output_plan: false

way_point_target_coefficient: 1000.
number_of_moves: 0
move_distance: 0.5